metricbeat.modules:
  - module: prometheus
    enabled: true
    period: 10s  # Set the interval for metric collection (adjust as needed)
    hosts: ["192.168.0.102:8080"]  # The address where your Java application exposes metrics

output.elasticsearch:
  hosts: ["elasticsearch:9200"]  # Replace with your Elasticsearch endpoint